# fly.toml
app = "pm-in-ai"
primary_region = "fra"  # вибери найближчий регіон (fra, waw, cdg, lhr, etc.)

[build]
  # Ми вже маємо Dockerfile, тож build section можна лишити порожнім

[env]
  # UI має звертатись до API через публічний порт 8080 цього ж застосунку
  BACKEND_URL = "http://pm-in-ai.fly.dev:8080"
  STREAMLIT_SERVER_HEADLESS = "true"
  STREAMLIT_BROWSER_GATHER_USAGE_STATS = "false"
  PYTHONUNBUFFERED = "1"

# --- СЕРВІС UI (Streamlit) на 80/443 ---
[[services]]
  internal_port = 8501
  protocol = "tcp"

  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    hard_limit = 50
    soft_limit = 25
    type = "connections"

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    method = "GET"
    path = "/"
    protocol = "http"
    tls_skip_verify = false
    grace_period = "10s"

# --- СЕРВІС API (FastAPI) на 8080/8443 ---
[[services]]
  internal_port = 8000
  protocol = "tcp"

  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 8080   # HTTP доступ до API: https://pm-in-ai.fly.dev:8080
    handlers = ["http"]

  [[services.ports]]
    port = 8443   # TLS порт (не обов'язково використовувати)
    handlers = ["tls", "http"]

  [services.concurrency]
    hard_limit = 100
    soft_limit = 50
    type = "connections"

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    method = "GET"
    path = "/health"
    protocol = "http"
    tls_skip_verify = false
    grace_period = "10s"
