# fly.toml
app = "pm-in-ai-v2"
primary_region = "fra"  # вибери найближчий регіон (fra, waw, cdg, lhr, etc.)

[build]
  # Ми вже маємо Dockerfile, тож build section можна лишити порожнім

[env]
  BACKEND_URL = "http://localhost:8000"
  STREAMLIT_SERVER_HEADLESS = "true"
  STREAMLIT_BROWSER_GATHER_USAGE_STATS = "false"
  PYTHONUNBUFFERED = "1"

# --- СЕРВІС UI (Streamlit) на 80/443 ---
[[services]]
  internal_port = 8501
  protocol = "tcp"

  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 0

  [[services.ports]]
    port = 80
    handlers = ["http"]

  [[services.ports]]
    port = 443
    handlers = ["tls", "http"]

  [services.concurrency]
    hard_limit = 50
    soft_limit = 25
    type = "connections"

  [[services.http_checks]]
    interval = "10s"
    timeout = "2s"
    method = "GET"
    path = "/"
    protocol = "http"
    grace_period = "60s"
