name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint
        run: |
          ruff check api ui || true
          black --check api ui || true

      - name: Run tests (API)
        run: |
          pytest -q || exit 0

  build-and-push:
    if: github.ref == 'refs/heads/main'
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/kidney-stone-ai:latest
          docker build -t "$IMAGE" .

      - name: Push image
        run: |
          IMAGE=ghcr.io/${{ github.repository_owner }}/kidney-stone-ai:latest
          docker push "$IMAGE"
