name: CI & Deploy to Fly.io

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Lint & Tests
        run: |
          python -m pip install ruff black pytest || true
          ruff check api ui || true
          black --check api ui || true
          pytest -q || true

  deploy:
    if: github.ref == 'refs/heads/main'
    needs: test-build
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Setup Flyctl
        uses: superfly/flyctl-actions/setup-flyctl@v1

      - name: Deploy to Fly
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          FLY_APP_NAME: ${{ vars.FLY_APP_NAME }}
        run: |
          # Переконайся, що в fly.toml app = FLY_APP_NAME
          sed -i "s/app = \".*\"/app = \"${FLY_APP_NAME}\"/" fly.toml
          # Деплой з віддаленим білдом (на builder Fly). Використовує Dockerfile з кореня.
          flyctl deploy --remote-only --build-arg BUILDKIT_INLINE_CACHE=1
